### ISSUE TITLE
Ideias necessárias para criar o mvp

### ISSUE THREAD

**Issue by isaqueveras** [avaliations/mvp#5]
# Frontend
Construir o frontend utilizando [nextjs](https://nextjs.org/) com o [chakra ui](https://chakra-ui.com/) para estilizar o layout.

### Profissionais
  - [ ] [:link:](https://github.com/avaliations/mvp/issues/1) Listar profissionais
  - [ ] [:link:](https://github.com/avaliations/mvp/issues/2) Cadastrar um profissional
  - [ ] [:link:](https://github.com/avaliations/mvp/issues/3) Editar um profissional
  - [ ] [:link:](https://github.com/avaliations/mvp/issues/4) Excluir o profissional

### Profissionais

# Backend
Construir uma base simples em [Golang](https://pkg.go.dev/) para fazer as rotas basicas do sistema e utilizar [PostgreSQL](https://www.postgresql.org/) para o banco de dados.

### Profissionais
  - [ ] [:link:](https://github.com/avaliations/mvp/issues/1) Listar profissionais
  - [ ] [:link:](https://github.com/avaliations/mvp/issues/2) Cadastrar um profissional
  - [ ] [:link:](https://github.com/avaliations/mvp/issues/3) Editar um profissional
  - [ ] [:link:](https://github.com/avaliations/mvp/issues/4) Excluir o profissional
